# For more information: https://laravel.com/docs/tintuc247
version: '3'
services:
    webserver:
        build:
            context: ./docker/php-7.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: 'www-data'
        # image: hatv1592/tintuc247:1.0
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: 'www-data'
            LARAVEL_tintuc247: 1
        volumes:
            - './:/var/www/html'
            - './docker/php-7.4/conf/nginx-site.conf:/etc/nginx/sites-available/default.conf'
        networks:
            - tintuc247
        env_file:
            - .env
        depends_on:
            - mysql
            # - pgsql
            - redis
            # - selenium
    # selenium:
    #     image: 'selenium/standalone-chrome'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - tintuc247
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'tintuc247mysql:/var/lib/mysql'
        networks:
            - tintuc247
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
#    pgsql:
#        image: postgres:13
#        ports:
#            - '${FORWARD_DB_PORT:-5432}:5432'
#        environment:
#            PGPASSWORD: '${DB_PASSWORD:-secret}'
#            POSTGRES_DB: '${DB_DATABASE}'
#            POSTGRES_USER: '${DB_USERNAME}'
#            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
#        volumes:
#            - 'tintuc247postgresql:/var/lib/postgresql/data'
#        networks:
#            - tintuc247
#        healthcheck:
#          test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'tintuc247redis:/data'
        networks:
            - tintuc247
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    # memcached:
    #     image: 'memcached:alpine'
    #     ports:
    #         - '11211:11211'
    #     networks:
    #         - tintuc247
    # mailhog:
    #     image: 'mailhog/mailhog:latest'
    #     ports:
    #         - '${FORWARD_MAILHOG_PORT:-1025}:1025'
    #         - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    #     networks:
    #         - tintuc247
networks:
    tintuc247:
        driver: bridge
volumes:
    tintuc247mysql:
        driver: local
#    tintuc247postgresql:
#        driver: local
    tintuc247redis:
        driver: local
